version: "3"
services:
  db2_seg_1:
    image: greenplum_4_seg:6.13.0
    build: .
    environment:
       - GP_NODE=segment
    hostname: db2_seg_1
    command: tail -f /dev/null
    volumes:
      - /data2/docker-disk/share-data/greenplum:/data/
    networks:
      - greenplum_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == hadoop1]
    sysctls:
      kernel.sem: "500 2048000 200 4096"

  db2_seg_2:
    image: greenplum_4_seg:6.13.0
    build: .
    environment:
       - GP_NODE=segment
    hostname: db2_seg_2
    command: tail -f /dev/null
    volumes:
      - /data2/docker-disk/share-data/greenplum:/data
    networks:
      - greenplum_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == hadoop2]
    sysctls:
      kernel.sem: "500 2048000 200 4096"

  db2_seg_3:
    image: greenplum_4_seg:6.13.0
    build: .
    environment:
       - GP_NODE=segment
    hostname: db2_seg_3
    command: tail -f /dev/null
    volumes:
      - /data2/docker-disk/share-data/greenplum:/data
    networks:
      - greenplum_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == hadoop2]
    sysctls:
      kernel.sem: "500 2048000 200 4096"

  db2_seg_4:
    image: greenplum_4_seg:6.13.0
    build: .
    environment:
       - GP_NODE=segment
    hostname: db2_seg_4
    command: tail -f /dev/null
    volumes:
      - /data2/docker-disk/share-data/greenplum:/data
    networks:
      - greenplum_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == hadoop2]
    sysctls:
      kernel.sem: "500 2048000 200 4096"

  db2_standby_1:
    image: greenplum_4_seg:6.13.0
    build: .
    environment:
       - GP_NODE=standby
    hostname: db2_standby_1
    command: tail -f /dev/null
    volumes:
      - /data2/docker-disk/share-data/greenplum:/data
    ports:
      - "5433:5432"
    links:
      - db2_seg_1:seg1
      - db2_seg_2:seg2
    networks:
      - greenplum_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == jiuzhou2]
  db2_master_1:
    image: greenplum_4_seg:6.13.0
    build: .
    environment:
       - GP_NODE=master
       - HOSTFILE=hostlist
    hostname: db2_master_1
    command: tail -f /dev/null
    volumes:
      - /data2/docker-disk/share-data/greenplum:/data
    depends_on: 
      - db2_seg_1
      - db2_seg_2
      - db2_standby_1
    ports:
      - "5432:5432"
    links:
      - db2_seg_1:seg1
      - db2_seg_2:seg2
      - db2_standby_1:standby
    networks:
      - greenplum_net
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == jiuzhou1]

networks:
  greenplum_net:
    external: true

